spring:
  application:
    name: edge-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: ${PORT:8080}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      prefer-ip-address: false

zuul:
  ignored-services: '*'
  routes:
    api-user-service: /users/**
    api-pay-service: /pays/**
#    api-user:
#      path: /users/**
#      service-id: api-user-service
#    api-pay:
#      path: /pays/**
#      service-id: api-pay-service
#    api-user-service:
#      path: /users/**
#      url: http://localhost:8080/
#    api-pay-service:
#      path: /pays/**
#      url: http://localhost:8081/


