spring:
  application:
    name: edge-service

server:
  port: ${port:8080}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      prefer-ip-address: false

zuul:
  ignored-services: '*'
  routes:
    api-user-service: /users/**
    api-pay-service: /pays/**
#    api-user-service:
#      path: /users/**
#      url: http://localhost:8080/
#    api-pay-service:
#      path: /pays/**
#      url: http://localhost:8081/


