spring:
  application:
    name: trace-service

server:
  port: ${port:9411}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      prefer-ip-address: false