spring:
  application:
    name: discovery-service

server:
  port: ${PORT:8761}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    com.weproud: debug