spring:
  application:
    name: discovery-service
  boot:
    admin:
      url: http://localhost:8762

server:
  port: ${PORT:8761}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    org.springframework:
      boot: info
    com.weproud: debug