spring:
  application:
    name: admin-service
#  boot:
#    admin:
#      notify:
#        telegram:
#          chat-id: <your-chat-id>
#          bot-token: <your-bot-token>

server:
  port: 8762

management:
  port: ${server.port}
  security:
    enabled: false
#
#eureka:
#  client:
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
#  instance:
#    lease-renewal-interval-in-seconds: 10
#    prefer-ip-address: false

logging:
  level:
    com.weproud: debug