spring:
  application:
    name: config-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      server:
        git:
          uri: https://github.com/logan81k/spring-boot-cloud-sample.git

server:
  port: ${PORT:8888}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: false

logging:
  level:
    com.weproud: debug