spring:
  application:
    name: api-user-service

server:
  port: ${PORT:8082}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      prefer-ip-address: false

