spring:
  application:
    name: api-user-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  boot:
    admin:
      url: http://localhost:8762

server:
  port: ${PORT:8082}

management:
  port: ${server.port}
  security:
    enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: false

security:
  oauth2:
    client:
      client-id: femto
      client-secret: femtogames2018
    resource:
      id: oauth2-resource
      token-info-uri: http://localhost:9999/oauth/check_token

logging:
  file: ${spring.application.name}
  level:
    org.springframework:
      web: 'off'
      data: 'off'
      jmx: 'off'
      beans: 'off'
      boot: info
      security: info
    com.weproud: debug